### ISSUE TITLE
tests fail on my computer due to use of `setwd("~/GitHub/ccostr")`

### ISSUE THREAD

**Issue by joethorley** [HaemAalborg/ccostr#10]
tests fail on my computer due to use of 

setwd("~/GitHub/ccostr")
load(file = "tests/testthat/StataDataTest.Rdata")

http://r-pkgs.had.co.nz/data.html

https://github.com/openjournals/joss-reviews/issues/1593

**Comment by LarsHernandez** [comment]
I moved the test data to inst/extdata and used: 
![image](https://user-images.githubusercontent.com/16371910/62606382-6955a280-b8fc-11e9-8384-90f7e111c8be.png)

I think this works

**Comment by joethorley** [comment]
yes this is appropriate
