### ISSUE TITLE
Please .Rbuildignore non-standard files or place in appropriate directories

### ISSUE THREAD

**Issue by joethorley** [HaemAalborg/ccostr#12]
Non-standard files/directories found at top level:
    ‘README.Rmd’ ‘ccostrRef.bib’ ‘fig’ ‘img’ ‘paper.md’

https://github.com/openjournals/joss-reviews/issues/1593

**Comment by LarsHernandez** [comment]
Thanks for the comment, but Is this a problem for the JOSS submission? It would nice to keep these files there, or do i need two repositories?

**Comment by joethorley** [comment]
You can keep them there you just need to make sure R ignores them (without a NOTE) by listing them in .Rbuildignore

**Comment by LarsHernandez** [comment]
Finally got it fixed, i learned a lesson never to put spaces in Rbuildignore :S
