### ISSUE TITLE
please ensure simCostData() is automatically tested 

### ISSUE THREAD

**Issue by joethorley** [HaemAalborg/ccostr#13]

**Comment by joethorley** [comment]
Currently running testthat does not automatically result in test coverage

http://r-pkgs.had.co.nz/tests.html#test-structure

https://github.com/openjournals/joss-reviews/issues/1593

**Comment by LarsHernandez** [comment]
You mean the coverage of the estimators right? This could be done, and also with the bias, but it is computationally heavy unless i give the test statements large error intervals. Any thoughts on this @rfbrondum @mboegsted

**Comment by joethorley** [comment]
I don't mean the coverage of the estimators just that the function is called by the automatic tests to confirm its outputs match known outputs. Currently it isn't.

**Comment by LarsHernandez** [comment]
But aren't they? or maybe i don't understand what you mean:

Here from the test file the ccmean function is used on the simulated data to calculate estimates and compare to the known outputs
![image](https://user-images.githubusercontent.com/16371910/62924789-2179c400-bdb1-11e9-83bf-535f84650a53.png)

**Comment by LarsHernandez** [comment]
Oh, i think i understand now, and i have added a test to show similarity to the stored data:

![image](https://user-images.githubusercontent.com/16371910/62927006-f5ad0d00-bdb5-11e9-876e-c7ec777803d3.png)

**Comment by joethorley** [comment]
Great - thanks - FWIW you can automatically test % coverage (and see which functions are untested) using 

https://codecov.io

**Comment by LarsHernandez** [comment]
Thanks, due to problems with access to organisations Github i run it in on a fork, it seems to work but i know it is not optimal as i will have to keep the fork up to date
