### ISSUE TITLE
please include StataDataTest.Rdata in appropriate directory

### ISSUE THREAD

**Issue by joethorley** [HaemAalborg/ccostr#14]
please include StataDataTest.Rdata in appropriate directory

http://r-pkgs.had.co.nz/data.html

https://github.com/openjournals/joss-reviews/issues/1593

**Comment by LarsHernandez** [comment]
From the link it says:
![image](https://user-images.githubusercontent.com/16371910/62602663-84241900-b8f4-11e9-8c1a-5d99267947bf.png)

the file i include is 401kb, i'm not sure if this is considered small? 

![image](https://user-images.githubusercontent.com/16371910/62602815-e67d1980-b8f4-11e9-811a-cd0d8041f589.png)

The stata files (.dta) in the StataTestCcostr folder i will delete, but in the directory i also have two more files, one text file with the stata code i ran, and one with the code to generate the data, should i just remove the whole folder?

![image](https://user-images.githubusercontent.com/16371910/62602838-f0068180-b8f4-11e9-821f-a0411ef0ecbe.png)

**Comment by LarsHernandez** [comment]
I moved the StataDataTest file to fix the relative path issue, still not sure if i should still include the scripts to replicate the data in R and estimation in Stata..

**Comment by joethorley** [comment]
The limit for an R package is 5MB so you are fine. Just put everything in data_raw.

The best way to setup is using

`usethis::use_data_raw()`

**Comment by joethorley** [comment]
and then use `usethis::use_data()` in a script in data raw to import the data into the package.

**Comment by LarsHernandez** [comment]
I've tried to use the usethis approach, but i've had some problems getting it to work. I've moved some things around and i think the datastructure is ok, and it works, so i don't think i'll look more into it for now, but thanks for the suggestion :)
