### ISSUE TITLE
estimates matching hcost

### ISSUE THREAD

**Issue by tgerke** [HaemAalborg/ccostr#20]
The paper states that the estimates from ccostr give similar results to Stata's hcost function. Why are they not identical? Were any comparisons made against the SAS macros?

**Comment by LarsHernandez** [comment]
That is a wrong phrasing in the paper, i'll correct it. They give identical results given you set the interpolation term. The testfiles includes hardcoded results from hcost, and they all pass.

**Comment by LarsHernandez** [comment]
I'm looking into comparing with the SAS macro, hopefully i get something identical. If i get it to work i'll include that in the testfiles
