### ISSUE TITLE
Order of confidence interval limits

### ISSUE THREAD

**Issue by mboegsted** [HaemAalborg/ccostr#3]
When running ccmean it would be nicer if the lower bound of the confidence interval comes first.

**Comment by LarsHernandez** [comment]
Yes, i will look into it later

**Comment by rfbrondum** [comment]
Should we rename them 2.5% and 97.5% as confint() does?

**Comment by LarsHernandez** [comment]
We can also go by what survival does, which is either from a basic print:
![image](https://user-images.githubusercontent.com/16371910/60866344-621d7500-a228-11e9-8d7d-6b2b4c879d71.png)

or when using a summary:
![image](https://user-images.githubusercontent.com/16371910/60866363-6fd2fa80-a228-11e9-8108-c8a8bcc9d93a.png)

**Comment by LarsHernandez** [comment]
Changed name and order to: 0.95LCL  0.95UCL
