### ISSUE TITLE
SD or SE

### ISSUE THREAD

**Issue by mboegsted** [HaemAalborg/ccostr#4]
In the output of ccmean both SD (in the table) and SE (for the mean survival) is used. I suggest to use SE in the tabel. We could consider writing Std. Error, as this is what anova for instance use.

**Comment by LarsHernandez** [comment]
Hcost uses  _Std. Err._ but I like _SE_ more, Rasmus any thoughts?

**Comment by rfbrondum** [comment]
I am fine with either as long as its consistent.
