### ISSUE TITLE
Vignettes will not install on MAC

### ISSUE THREAD

**Issue by mboegsted** [HaemAalborg/ccostr#5]
RStudio version: 1.2.1335
R version: 3.6.1 (2019-07-05)

> devtools::install_github("HaemAalborg/ccostr", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"))
Skipping install of 'ccostr' from a github remote, the SHA1 (d4311d1c) has not changed since last install.
  Use `force = TRUE` to force installation
> devtools::install_github("HaemAalborg/ccostr", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"), force = TRUE)
Downloading GitHub repo HaemAalborg/ccostr@master
These packages have more recent versions available.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: vctrs (0.1.0 -> 0.2.0) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
3
✔  checking for file ‘/private/var/folders/20/l2vlcfwn04lbcd4gcllh707m0000gn/T/RtmpS3kDuD/remotesfcea7a93e6de/HaemAalborg-ccostr-d4311d1/DESCRIPTION’ ...
─  preparing ‘ccostr’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
   Loading required namespace: ccostr
─  saving partial Rd database (1.5s)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘ccostr_0.1.0.tar.gz’
   
* installing *source* package ‘ccostr’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ccostr)
>

**Comment by rfbrondum** [comment]
I have a suspicion this is related to something in devtools. Are you using the latest version of devtools? Can you build vignettes for other packages on github, i.e. hemaClass?

**Comment by mboegsted** [comment]
This command helped a lot, i.e. forcing devtools to install build the vignettes. Maybe the README should be changed?

devtools::install_github("HaemAalborg/ccostr", force=TRUE, build_vignettes = TRUE)

**Comment by LarsHernandez** [comment]
I thinks this comes down to the version of devtools, and this was the old way it used to be, i guess if not already the devtools should be updated to fix it soon also on MAC
