### ISSUE TITLE
I do not understand the outcome of this example

### ISSUE THREAD

**Issue by mboegsted** [HaemAalborg/ccostr#6]
> df <- data.frame(
+   id =    c(1,1,2,3,3,3),
+   cost =  c(1,1,1,1,1,1),
+   start = c(0,1,0,0,1,2), 
+   stop =  c(1,2,1,1,2,3),
+   delta = c(0,0,1,1,1,1),
+   surv =  c(5,5,5,5,5,5)
+ )
> ccmean(df)
ccostr - Estimates of mean cost with censored data

  Observations Induviduals Events Limits TotalTime MaxSurv
N            6           3      3      5        15       5

   Estimate  Variance        SD    95UCI     95LCI
AS        2 0.3333333 0.5773503 3.131607 0.8683935
CC        2 0.3333333 0.5773503 3.131607 0.8683935
BT        2 0.2222222 0.4714045 2.923953 1.0760471
ZT        2 0.2222222 0.4714045 2.923953 1.0760471

Mean survival time: 5 With SE: 0

**Comment by rfbrondum** [comment]
ccmean automatically sets the limit (L) to the max survival time, if not specified, so delta for id 1 is set to 1 as it is fully observed until T = 5, meaning no ids are censored within the timeframe, and AS = CC, BT = ZT.

Maybe should call event something else in the first line of the output. What we are really counting is fully observed individuals within the timeframe.

**Comment by mboegsted** [comment]
Ok, I see!
