### ISSUE TITLE
contributors are not credited

### ISSUE THREAD

**Issue by joethorley** [HaemAalborg/ccostr#9]
Can @LarsHernandez add @LasseHjort and @rfbrondum as ctb or aut as appropriate?

http://r-pkgs.had.co.nz/description.html#author

https://github.com/openjournals/joss-reviews/issues/1593

**Comment by LarsHernandez** [comment]
I updated the DESCRIPTION file

![image](https://user-images.githubusercontent.com/16371910/62601957-d9f7c180-b8f2-11e9-8419-9431f504d205.png)
